//All the includes
#include<stdio.h>
#include<stdlib.h>
#include<ctype.h>
#include<time.h>

#include"server.h"

int main(void){
	//The main function
	//Creating instances for all the structures
	//And defining the variables
    airport AirPort;
    int i, numOfPlanes, presentTime, TotalTime ;
    
    plane temp;
    //Initializing the airport
    initializeAirport(&AirPort);
	//Starting
    start(&TotalTime);
	//Outer for loop manages the number of iterations, which is a count of time
	//Effectively, 1 iteration is 1 unit of time
    for(presentTime = 1 ; presentTime <= TotalTime ; presentTime++){
        numOfPlanes = randomnumber();
        //The num of planes for every iteration is
		//randomly generated by using a slightly complex random function
		for(i = 0 ; i < numOfPlanes ; i++){
			//Generation of planes randomly 
            createNewPlane(&AirPort, presentTime, DEPART);
        	//For every iteration a new plane will be generated
        	//and added to the landing queue if and only if
        	//the airport is empty and no plane needs to land
            if(isFullAirport(AirPort, DEPART))
               refuseLand(&AirPort);
               //The plane will be refused to be allowed to
               //take off if the airport is not empty
            else
               airportAddToQueue(&AirPort, DEPART);
               //Will be alllowed to take off if the airport is empty
        }


        numOfPlanes = randomnumber();
		
        for(i = 0 ; i < numOfPlanes ; i++){
        	//For every iteration a new plane will be generated
        	//and added to the landing queue
            createNewPlane(&AirPort, presentTime, ARRIVE);
			airportAddToQueue(&AirPort, ARRIVE);
        }


        //Here, the generation of planes is complete
        //Its time to either land or take off
        if(!(isEmptyAirport(AirPort, ARRIVE))){
        	//If landing is possible
            while(!isEmptyAirport(AirPort, ARRIVE)){
            	//All the planes that need to land will land
                temp = airportPopQueue(&AirPort, ARRIVE);
                land(&AirPort, temp, presentTime);
            }
        } else if(!(isEmptyAirport(AirPort, DEPART))) {
        	//Take off will not be allowed for all at the same time
            temp = airportPopQueue(&AirPort, DEPART);
            fly(&AirPort, temp, presentTime);
    	}else{
    		//If there is no plane to land or takeoff,
    		//the runway is idle
        	idle(&AirPort, presentTime);
		}
		delay(0.25);
		//mimicking the sleep function

    }
	//After each iteration, a unit of time passes

	//Calling the result function
    Result(&AirPort, TotalTime);
	//clearing the screen
    clrscr();
    
	return 0;
}
